-- --------------------------------------------------------
-- HOST:                         127.0.0.1
-- VERSIÓN DEL SERVIDOR:         10.9.2-MARIADB - MARIADB.ORG BINARY DISTRIBUTION
-- SO DEL SERVIDOR:              WIN64
-- HEIDISQL VERSIÓN:             12.3.0.6589
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES UTF8 */;
/*!50503 SET NAMES UTF8MB4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- VOLCANDO ESTRUCTURA DE BASE DE DATOS PARA SITCDQA
DROP DATABASE IF EXISTS svbdqa;
CREATE DATABASE IF NOT EXISTS `SVBDQA` /*!40100 DEFAULT CHARACTER SET LATIN1 */;
USE `SVBDQA`;

CREATE TABLE IF NOT EXISTS `SVC_NIVEL_OFICINA` (
  `ID_OFICINA` INT(2) NOT NULL ,
  `DES_NIVELOFICINA`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_OFICINA`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_DELEGACION` (
  `ID_DELEGACION` INT(2) NOT NULL ,
  `DES_DELEGACION`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_DELEGACION`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE if not exists SVC_CP (CVE_CODIGO_POSTAL INT (6), 
des_asenta VARCHAR(30) DEFAULT NULL,
des_tipo_asenta VARCHAR(30) DEFAULT NULL,
Des_mnpio  VARCHAR(30) DEFAULT NULL,
des_estado  VARCHAR(30) DEFAULT NULL,
des_ciudad VARCHAR(30) DEFAULT NULL,
des_CP VARCHAR(30) DEFAULT NULL,
cve_estado  INT (6),
cve_oficina  INT (6),
cve_CP   INT (6),
cve_tipo_asenta  INT (6),
cve_mnpio  INT (6),
id_asenta_cpcons  INT (6),
des_zona VARCHAR(30) DEFAULT NULL,
cev_ciudad  INT (6));

CREATE TABLE IF NOT EXISTS `SVC_VELATORIO` (
  `ID_VELATORIO` INT(2) NOT NULL AUTO_INCREMENT,
  `NOM_VELATORIO` VARCHAR(30) DEFAULT NULL,
  `ID_USUARIO` INT(5) NOT NULL, -- ADMINISTRADOR
  NOM_RESPO_SANITARIO VARCHAR(50) DEFAULT NULL,
CVE_ASIGNACION INT(1),
DES_CALLE VARCHAR(200),
NUM_EXT INT(20),
CVE_CODIGO_POSTAL INT (6),
-- DES_COLONIA  VARCHAR(200), 
-- DES_MUNICIPIO  VARCHAR(200),
-- DES_ESTADO  VARCHAR(200),
NUM_TELEFONO  VARCHAR(20),
IND_ESTATUS BIT ,  
 `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID_VELATORIO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_SALA` (
  `ID_SALA` INT(2) NOT NULL AUTO_INCREMENT,
  `NOM_SALA` VARCHAR(30) DEFAULT NULL,
  `ID_USUARIO` INT(5) NOT NULL, -- ADMINISTRADOR
  NOM_RESPO_SANITARIO VARCHAR(50) DEFAULT NULL,
  IND_TIPO_SALA BIT, 
  /*o	De cremación
o	De embalsamamiento*/
  CAN_CAPACIDAD INT(1),
  IND_DISPONIBILIDAD BIT,  
  `ID_VELATORIO` INT(2),
   `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID_SALA`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;


CREATE TABLE IF NOT EXISTS `SVC_CAPILLA` (
  `ID_CAPILLA` INT(2) NOT NULL AUTO_INCREMENT,
  `NOM_CAPILLA` VARCHAR(30) DEFAULT NULL,
  CAN_CAPACIDAD INT(5),
  NUM_LARGO INT(5),
  NUM_ALTO INT(5),
`ID_VELATORIO` INT(2),
 `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID_CAPILLA`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_ROL` (
  `ID_ROL` INT(2) NOT NULL,
  `DES_ROL`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_ROL`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_PERMISO` (
  `ID_PERMISO` INT(2) NOT NULL ,
  `DES_PERMISO`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_PERMISO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_FUNCIONALIDAD` (
  `ID_FUNCIONALIDAD` INT(2) NOT NULL ,
  `DES_FUNCIONALIDAD`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_FUNCIONALIDAD`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
 CREATE TABLE IF NOT EXISTS `SVC_FUNCIONALIDAD_SERVICIO` (
  `ID_SERVICIO` INT(2) NOT NULL  AUTO_INCREMENT,
  `NOM_SERVICIO`  VARCHAR(20) NOT NULL,
     `ID_PERMISO` INT(2) NOT NULL ,
      `DES_URL` VARCHAR(50) DEFAULT NULL,
      `CVE_ESTATUS` BIT(1) NOT NULL,
       `DES_DESCRIPCION` VARCHAR(30) DEFAULT NULL,
         `ID_FUNCIONALIDAD` INT(2) NOT NULL ,
  PRIMARY KEY (`ID_SERVICIO`),
  CONSTRAINT `SVC_FUNCIONALIDAD_SERVICIOID_PERMISO` FOREIGN KEY (`ID_PERMISO`) REFERENCES `SVC_PERMISO` (`ID_PERMISO`),
  CONSTRAINT `SVC_FUNCIONALIDAD_SERVICIOID_FUNCIONALIDAD` FOREIGN KEY (`ID_FUNCIONALIDAD`) REFERENCES `SVC_FUNCIONALIDAD` (`ID_FUNCIONALIDAD`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3; 

CREATE TABLE  IF NOT EXISTS `SVC_PARAMETRO_SISTEMA` (
`ID_PARAMETRO` INT(11) NOT NULL,
`ID_PARAMETRO_PADRE` INT(11) NOT NULL,
`DES_PARAMETRO` VARCHAR(128) DEFAULT NULL,
`TIP_PARAMETRO` BLOB(128) DEFAULT NULL,
FEC_MODIFICACION DATE DEFAULT NULL,
`CVE_ESTATUS` BIT(1) NOT NULL
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_ROL_FUNCIONALIDAD_PERMISO` (
`ID_ROL` INT(2) NOT NULL,
  `ID_FUNCIONALIDAD` INT(2) NOT NULL ,
  `ID_PERMISO` INT(2) NOT NULL,
    `CVE_ESTATUS` BIT(1) NOT NULL,
      `CVE_MATRICULA` VARCHAR(20) DEFAULT NULL ,
  `FEC_CREACION` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `CVE_MATRICULA_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `CVE_MATRICULA_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID_ROL,`ID_FUNCIONALIDAD`,ID_PERMISO) -- ,
 -- CONSTRAINT `SVC_ROLFUNCIONPERMIID_ROL` FOREIGN KEY (`ID_ROL`) REFERENCES `SVC_ROL` (`ID_ROL`),
 -- CONSTRAINT `SVC_ROLFUNCIONPERMIID_FUNCIONALIDAD` FOREIGN KEY (`ID_FUNCIONALIDAD`) REFERENCES `SVC_FUNCIONALIDAD` (`ID_FUNCIONALIDAD`),
 -- CONSTRAINT `SVC_ROLFUNCIONPERMIID_PERMISO` FOREIGN KEY (`ID_PERMISO`) REFERENCES `SVC_PERMISO` (`ID_PERMISO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_ROL_NIVEL_OFICINA` (
  `ID_ROL` INT(2) NOT NULL ,
   ID_OFICINA INT(2) NOT NULL ,
  PRIMARY KEY (`ID_ROL`,ID_OFICINA) -- ,
 -- CONSTRAINT `SVC_ROL_NIVEL_OFICINAID_ROL` FOREIGN KEY (`ID_ROL`) REFERENCES `SVC_ROL` (`ID_ROL`),
 -- CONSTRAINT `SVC_ROL_NIVEL_OFICINAID_OFICINA` FOREIGN KEY (`ID_OFICINA`) REFERENCES `SVC_NIVEL_OFICINA` (`ID_OFICINA`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVT_USUARIOS` (
  `ID_USUARIO` INT(5) NOT NULL AUTO_INCREMENT,
  DES_CURP VARCHAR(18) NOT NULL,
  `CVE_MATRICULA` VARCHAR(10) NOT NULL,
  `NOM_USUARIO` VARCHAR(50) NOT NULL,
  `NOM_APELLIDO_PATERNO` VARCHAR(50) NOT NULL,
  `NOM_APELLIDO_MATERNO` VARCHAR(50) NOT NULL,
  `FEC_NACIMIENTO` DATETIME DEFAULT NULL,
  DES_CORREOE VARCHAR(50) NOT NULL,
  `ID_OFICINA` INT(1) NOT NULL,
  ID_DELEGACION INT(5) NOT NULL,
  ID_VELATORIO INT(5) NOT NULL,
  ID_ROL INT(2) NOT NULL,
  `CVE_ESTATUS` BIT(1) NOT NULL,
  CVE_USUARIO  VARCHAR(20) NOT NULL,
  CVE_CONTRASENIA VARCHAR(20) NOT NULL,
 `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID_USUARIO`) -- ,
-- CONSTRAINT `SVT_USUARIOSID_OFICINA` FOREIGN KEY (`ID_OFICINA`,ID_ROL) REFERENCES `SVC_ROL_NIVEL_OFICINA` (`ID_OFICINA`,ID_ROL),
-- CONSTRAINT `SVT_USUARIOSID_DELEGACION` FOREIGN KEY (`ID_DELEGACION`) REFERENCES `SVC_DELEGACION` (`ID_DELEGACION`),
-- CONSTRAINT `SVT_USUARIOSID_VELATORIO` FOREIGN KEY (`ID_VELATORIO`) REFERENCES `SVC_VELATORIO` (`ID_VELATORIO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_TIPO_PROVEEDOR` (
  `ID_TIPO_PROVEEDOR` INT(2) NOT NULL ,
  `DES_TIPO_PROVEEDOR`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_TIPO_PROVEEDOR`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
INSERT INTO SVC_TIPO_PROVEEDOR (ID_TIPO_PROVEEDOR,DES_TIPO_PROVEEDOR) VALUES (1,'Subrogados'); 
INSERT INTO SVC_TIPO_PROVEEDOR (ID_TIPO_PROVEEDOR,DES_TIPO_PROVEEDOR) VALUES (2,'consignantes'); 
INSERT INTO SVC_TIPO_PROVEEDOR (ID_TIPO_PROVEEDOR,DES_TIPO_PROVEEDOR) VALUES (3,'instituto');

CREATE TABLE IF NOT EXISTS `SVT_PROVEEDOR` (
  `ID_PROVEEDOR` INT(2) NOT NULL ,
   NOM_PROVEEDOR VARCHAR(50) NOT NULL ,
   NOM_BANCO VARCHAR(20) NOT NULL ,
   CVE_BANCARIA INT(40) NOT NULL ,
   ID_TIPO_PROVEEDOR INT(2) DEFAULT NULL,
   DES_RFC VARCHAR(12) NOT NULL ,
   DES_CURP VARCHAR(12) NOT NULL ,
	DES_TIPO_CONTRATO VARCHAR(80) NOT NULL ,
	FEC_VIGENCIA DATE DEFAULT NULL,
	DES_DIRECCION VARCHAR(200) NOT NULL ,
	NUM_EXTERIOR INT (10)  DEFAULT NULL,
	NUM_INTERIOR INT (10)  DEFAULT NULL,
   CVE_CODIGO_POSTAL INT (6),
   `ID_PROVEEDOR_DIREC_REFE` INT(2) NOT NULL ,
   DES_DIRECCION_REFE VARCHAR(200) NOT NULL ,
	NUM_EXTERIOR_REFE INT (10)  DEFAULT NULL,
	NUM_INTERIOR_REFE INT (10)  DEFAULT NULL,
   CVE_CODIGO_POSTAL_REFE INT (6),
	NUM_TELEFONO INT (50) DEFAULT NULL ,
   DES_CORREOE VARCHAR(50) DEFAULT NULL,
	DES_REGIMEN VARCHAR(50) DEFAULT NULL,
   DES_REPRESENTANTE_LEGAL VARCHAR(50) DEFAULT NULL,
  `CVE_ESTATUS` BIT(1) NOT NULL,
   `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID_PROVEEDOR) -- ,
  -- CONSTRAINT `SVT_PROVEEDORID_TIPO_PROVEEDOR` FOREIGN KEY (`ID_TIPO_PROVEEDOR`) REFERENCES `SVC_TIPO_PROVEEDOR` (`ID_TIPO_PROVEEDOR`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;



CREATE TABLE IF NOT EXISTS `SVT_PROVEEDOR_DIREC_REFE` (
  `ID_PROVEEDOR_DIREC_REFE` INT(2) NOT NULL ,
   DES_DIRECCION_REFE VARCHAR(200) NOT NULL ,
	NUM_EXTERIOR_REFE INT (10)  DEFAULT NULL,
	NUM_INTERIOR_REFE INT (10)  DEFAULT NULL,
   CVE_CODIGO_POSTAL_REFE INT (6), `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID_PROVEEDOR_DIREC_REFE) -- ,
 -- CONSTRAINT `SVC_ROL_NIVEL_OFICINAID_ROL` FOREIGN KEY (`ID_ROL`) REFERENCES `SVC_ROL` (`ID_ROL`),
 -- CONSTRAINT `SVC_ROL_NIVEL_OFICINAID_OFICINA` FOREIGN KEY (`ID_OFICINA`) REFERENCES `SVC_NIVEL_OFICINA` (`ID_OFICINA`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS `SVC_TIPO_SERVICIO` (
  `ID_TIPO_SERVICIO` INT(2) NOT NULL ,
  `DES_TIPO_SERVICIO`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_TIPO_SERVICIO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;


CREATE TABLE IF NOT EXISTS `SVC_CAP_PART_PRESU` (
  `ID_CAP_PART_PRESU` INT(2) NOT NULL ,
  	NUM_CAPITULO INT(5) NOT NULL,
   `DES_CAP_PART_PRESU`  VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_CAP_PART_PRESU`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  


CREATE TABLE IF NOT EXISTS `SVC_PARTIDA_PRESUPUESTAL` (
  `ID_PART_PRESUPUESTAL` INT(2) NOT NULL ,
  `DES_PART_PRESUPUESTAL`  VARCHAR(20) NOT NULL,
`DES_DET_PART_PRESUPUESTAL`  VARCHAR(4000) NOT NULL,
   `ID_CAP_PART_PRESU` INT(2) NOT NULL ,
  PRIMARY KEY (`ID_PART_PRESUPUESTAL`),
   CONSTRAINT `SVC_PARTIDA_PRESUPUESTALID_CAP_PART_PRESU` FOREIGN KEY (`ID_CAP_PART_PRESU`) REFERENCES `SVC_CAP_PART_PRESU` (`ID_CAP_PART_PRESU`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

INSERT INTO SVC_CAP_PART_PRESU(`ID_CAP_PART_PRESU`,NUM_CAPITULO,`DES_CAP_PART_PRESU`) VALUES (
1,2000,'2100 MATERIALES DE ADMINISTRACION, EMISION DE DOCUMENTOS Y ARTICULOS OFICIALES');

INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (
21101,'Materiales y útiles de oficina','Asignaciones destinadas a la adquisición de materiales, artículos diversos y equipos menores propios para el uso de las oficinas tales como: papelería, formas, libretas, carpetas y cualquier tipo de papel, vasos y servilletas desechables, limpia-tipos; útiles de escritorio como engrapadoras, perforadoras manuales, sacapuntas; artículos de dibujo, correspondencia y archivo; cestos de basura y otros productos similares. Incluye la adquisición de artículos de envoltura, sacos y valijas, entre otros.',1);

INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (21201,'Materiales y útiles de impresión y reproducción','Asignaciones destinadas a la adquisición de materiales utilizados en la impresión, reproducción y encuadernación, tales como: fijadores, tintas, pastas, logotipos y demás materiales y útiles para el mismo fin. Incluye rollos fotográficos.',1);
INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (21401,'Materiales y Utiles bienes','Asignaciones destinadas a la adquisición de insumos y equipos menores utilizados en el procesamiento, grabación e impresión de datos, así como los materiales para la limpieza y protección de los equipos tales como: tóner, medios ópticos y magnéticos, apuntadores y protectores, entre otros.',1);
INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (21601,'Material de limpieza','Asignaciones destinadas a la adquisición de materiales, artículos y enseres para el aseo, limpieza e higiene, tales como: escobas, jergas, detergentes, jabones y otros productos similares.',1);


INSERT INTO SVC_CAP_PART_PRESU(`ID_CAP_PART_PRESU`,NUM_CAPITULO,`DES_CAP_PART_PRESU`) VALUES (
2,2000,'ALIMENTOS Y UTENSILIOS');

INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (
22102,'Productos alimenticios para personas derivado de la prestacion de servicios publicos en unidades de salud, educativas, de readaptacion social y otras','Asignaciones destinadas a la adquisición de todo tipo de productos alimenticios y bebidas para la alimentación de personas, derivado de la ejecución de los programas institucionales de salud, seguridad social, educativos, culturales y recreativos, así como para cautivos y reos en proceso de readaptación social. Incluye la adquisición de alimentos y complementos nutricionales para su distribución a la población, así como la alimentación para repatriados y extraditados',2);
INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (22104,'Productos alimenticios','Asignaciones destinadas a la adquisición de todo tipo de productos alimenticios y bebidas manufacturados o no, independiente de la modalidad de compra o contratación, derivado de la ejecución de los programas institucionales tales como: salud, seguridad social, educativos, militares, culturales y recreativos, cautivos y reos en proceso de readaptación social, repatriados y extraditados, personal que realiza labores de campo o supervisión dentro del lugar de adscripción; derivado de programas que requieren permanencia de servidores públicos en instalaciones del ente público, así como en el desempeño de actividades extraordinarias en el cumplimiento de la función pública. Excluye Viáticos (partidas 375 y 376), gastos derivados del concepto 3800 Servicios Oficiales y 133 Horas Extraordinarias no justificadas.',2);
INSERT INTO SVC_PARTIDA_PRESUPUESTAL(
 `ID_PART_PRESUPUESTAL`,
  `DES_PART_PRESUPUESTAL`,
`DES_DET_PART_PRESUPUESTAL`,
   `ID_CAP_PART_PRESU`) VALUES 
   (22301,'Utensilios para el servicio de Alimentacion','Asignaciones destinadas a la adquisición de todo tipo de utensilios necesarios para proporcionar este servicio, tales como: vajillas, cubiertos, baterías de cocina, licuadoras, tostadoras, cafeteras, básculas y demás electrodomésticos y bienes consumibles en operaciones a corto plazo.',2);
 
  CREATE TABLE IF NOT EXISTS `SVC_CUENTA_PART_PRESU` (
  `ID_CUENTA_PART_PRESU` INT(2) NOT NULL ,
  	NUM_CUENTA_PART_PRESU INT(10) NOT NULL,
  PRIMARY KEY (`ID_CUENTA_PART_PRESU`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
  INSERT INTO SVC_CUENTA_PART_PRESU (ID_CUENTA_PART_PRESU,NUM_CUENTA_PART_PRESU)
  VALUES (1,512100100);
  INSERT INTO SVC_CUENTA_PART_PRESU (ID_CUENTA_PART_PRESU,NUM_CUENTA_PART_PRESU)
  VALUES (2,512100300);  
  INSERT INTO SVC_CUENTA_PART_PRESU (ID_CUENTA_PART_PRESU,NUM_CUENTA_PART_PRESU)
  VALUES (3,512200100);
  INSERT INTO SVC_CUENTA_PART_PRESU (ID_CUENTA_PART_PRESU,NUM_CUENTA_PART_PRESU)
  VALUES (4,512200200);


   CREATE TABLE IF NOT EXISTS `SVT_RELA_CUENTA_PART_PRESU` (
  `ID_CUENTA_PART_PRESU` INT(2) NOT NULL ,
  	ID_PART_PRESUPUESTAL INT(2) NOT NULL,
  PRIMARY KEY (`ID_CUENTA_PART_PRESU`,ID_PART_PRESUPUESTAL),
   CONSTRAINT `SVC_CUENTA_PART_PRESU1` FOREIGN KEY (`ID_CUENTA_PART_PRESU`) REFERENCES `SVC_CUENTA_PART_PRESU` (`ID_CUENTA_PART_PRESU`),
    CONSTRAINT `SVC_PARTIDA_PRESUPUESTAL1` FOREIGN KEY (`ID_PART_PRESUPUESTAL`) REFERENCES `SVC_PARTIDA_PRESUPUESTAL` (`ID_PART_PRESUPUESTAL`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;



  CREATE TABLE IF NOT EXISTS `SVC_CLAVES_PRODUCTOS_SERVICIOS` (
  `ID_PRODUCTOS_SERVICIOS` INT(2) NOT NULL ,
  	CVE_PRODUCTOS_SERVICIOS INT(10) NOT NULL,
  	DES_PRODUCTOS_SERVICIOS  VARCHAR(70) DEFAULT NULL ,
  	DES_UNIDAD_SAT  VARCHAR(15) DEFAULT NULL ,
  PRIMARY KEY (`ID_PRODUCTOS_SERVICIOS`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
CREATE TABLE IF NOT EXISTS SVT_SERVICIO (
	ID_SERVICIO INT(8)  NOT NULL AUTO_INCREMENT,
 	NOM_SERVICIO VARCHAR(70) DEFAULT NULL ,
   DES_DESCRIPCION VARCHAR(70) DEFAULT NULL , 
   ID_TIPO_SERVICIO INT(2)DEFAULT NULL ,
   ID_PART_PRESUPUESTAL INT(8) DEFAULT NULL,
    `ID_CUENTA_PART_PRESU` INT(2) NOT NULL ,
DES_OBSERVACIONES VARCHAR (70) DEFAULT NULL,
  `CVE_ESTATUS` BIT(1) NOT NULL,
 `ID_PRODUCTOS_SERVICIOS` INT(2) NOT NULL ,
  `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
   PRIMARY KEY (`ID_SERVICIO`),
    CONSTRAINT `SVT_SERVICIOID_TIPO_SERVICIO` FOREIGN KEY (`ID_TIPO_SERVICIO`) REFERENCES `SVC_TIPO_SERVICIO` (`ID_TIPO_SERVICIO`),
    CONSTRAINT `SVT_SERVICIOID_CUENRT_PRESUPUESTAL` FOREIGN KEY (`ID_CUENTA_PART_PRESU`,ID_PART_PRESUPUESTAL) REFERENCES `SVT_RELA_CUENTA_PART_PRESU` (`ID_CUENTA_PART_PRESU`,ID_PART_PRESUPUESTAL),
    CONSTRAINT `SVT_SERVICIOID_PRODUCTOS_SERVICIOS` FOREIGN KEY (ID_PRODUCTOS_SERVICIOS) REFERENCES `SVC_CLAVES_PRODUCTOS_SERVICIOS` (ID_PRODUCTOS_SERVICIOS)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

  CREATE TABLE IF NOT EXISTS `SVC_CATEGORIA_ARTICULO` (
  `ID_CATEGORIA_ARTICULO` INT(3) NOT NULL ,
  	DES_CATEGORIA_ARTICULO VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_CATEGORIA_ARTICULO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
  INSERT INTO SVC_CATEGORIA_ARTICULO (ID_CATEGORIA_ARTICULO,DES_CATEGORIA_ARTICULO) VALUES (1,'Ataúd.');
  INSERT INTO SVC_CATEGORIA_ARTICULO (ID_CATEGORIA_ARTICULO,DES_CATEGORIA_ARTICULO) VALUES (2,'Urna.');
  INSERT INTO SVC_CATEGORIA_ARTICULO (ID_CATEGORIA_ARTICULO,DES_CATEGORIA_ARTICULO) VALUES (3,'Cartucho.');
  INSERT INTO SVC_CATEGORIA_ARTICULO (ID_CATEGORIA_ARTICULO,DES_CATEGORIA_ARTICULO) VALUES (4,'Empaques traslado aéreo.');
  INSERT INTO SVC_CATEGORIA_ARTICULO (ID_CATEGORIA_ARTICULO,DES_CATEGORIA_ARTICULO) VALUES (5,'Bolsa para cadáver.');
  INSERT INTO SVC_CATEGORIA_ARTICULO (ID_CATEGORIA_ARTICULO,DES_CATEGORIA_ARTICULO) VALUES (6,'Otro.');

   
  
  CREATE TABLE IF NOT EXISTS `SVC_TIPO_ARTICULO` (
  `ID_TIPO_ARTICULO` INT(3) NOT NULL ,
  	DES_TIPO_ARTICULO VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_TIPO_ARTICULO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
  INSERT INTO SVC_TIPO_ARTICULO (ID_TIPO_ARTICULO,DES_TIPO_ARTICULO) VALUES (1,'funerario');
  INSERT INTO SVC_TIPO_ARTICULO (ID_TIPO_ARTICULO,DES_TIPO_ARTICULO) VALUES (2,'complementario');

  CREATE TABLE IF NOT EXISTS `SVC_TIPO_MATERIAL` (
  `ID_TIPO_MATERIAL` INT(3) NOT NULL ,
  	DES_TIPO_MATERIAL VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_TIPO_MATERIAL`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
  
    INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (1,'Madera.');
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (2,'Metal.');
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (3,'Madera ecológica (MDF O HDF).'); 
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (4,'Cartón corrugado.');
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (5,'Biodegradable.');
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (6,'Mármol.');
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (7,'Ónix.');
  INSERT INTO SVC_TIPO_MATERIAL (ID_TIPO_MATERIAL,DES_TIPO_MATERIAL) VALUES (8,'Otro.');

  
  
  CREATE TABLE IF NOT EXISTS `SVC_TAMANIO` (
  `ID_TAMANIO` INT(3) NOT NULL ,
  	DES_TAMANIO VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_TAMANIO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

  INSERT INTO SVC_TAMANIO (ID_TAMANIO,DES_TAMANIO) VALUES (1,'Infantil.');
  INSERT INTO SVC_TAMANIO (ID_TAMANIO,DES_TAMANIO) VALUES (2,'Adulto.');
  INSERT INTO SVC_TAMANIO (ID_TAMANIO,DES_TAMANIO) VALUES (3,'Jumbo.');
  INSERT INTO SVC_TAMANIO (ID_TAMANIO,DES_TAMANIO) VALUES (4,'Tambora.');
  INSERT INTO SVC_TAMANIO (ID_TAMANIO,DES_TAMANIO) VALUES (5,'Otro.');
 


  
  CREATE TABLE IF NOT EXISTS `SVC_CLASIFICACION_PRODUCTO` (
  `ID_CLASIFICACION_PRODUCTO` INT(3) NOT NULL ,
  	DES_CLASIFICACION_PRODUCTO VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_CLASIFICACION_PRODUCTO`)
  ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;
  
  INSERT INTO SVC_CLASIFICACION_PRODUCTO (ID_CLASIFICACION_PRODUCTO,DES_CLASIFICACION_PRODUCTO) VALUES (1,'Básica.');
  INSERT INTO SVC_CLASIFICACION_PRODUCTO (ID_CLASIFICACION_PRODUCTO,DES_CLASIFICACION_PRODUCTO) VALUES (2,'Intermedia.');
  INSERT INTO SVC_CLASIFICACION_PRODUCTO (ID_CLASIFICACION_PRODUCTO,DES_CLASIFICACION_PRODUCTO) VALUES (3,'Alta.');
  INSERT INTO SVC_CLASIFICACION_PRODUCTO (ID_CLASIFICACION_PRODUCTO,DES_CLASIFICACION_PRODUCTO) VALUES (4,'Otro.');


CREATE TABLE IF NOT EXISTS SVT_ARTICULO ( 
ID_ARTICULO INT (8) NOT NULL AUTO_INCREMENT,
ID_CATEGORIA_ARTICULO  INT(3) NOT NULL ,
ID_TIPO_ARTICULO  INT(3) NOT NULL ,
ID_TIPO_MATERIAL   INT(3) NOT NULL ,
ID_TAMANIO   INT(3) NOT NULL ,
`ID_CLASIFICACION_PRODUCTO` INT(3) NOT NULL ,
DES_MODELO_ARTICULO VARCHAR (70) NOT NULL,
DES_ARTICULO VARCHAR (70) NOT NULL, --
 	ID_PART_PRESUPUESTAL INT(2) NOT NULL,
`ID_CUENTA_PART_PRESU` INT(2) DEFAULT NULL ,
 `ID_PRODUCTOS_SERVICIOS` INT(2) NOT NULL ,
  `CVE_ESTATUS` BIT(1) NOT NULL,
   `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (ID_ARTICULO)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB3;

CREATE TABLE IF NOT EXISTS SVT_ARTICULO_MEDIDA (
ID_ARTICULO_MEDIADA INT(5) NOT NULL AUTO_INCREMENT,
ID_ARTICULO INT (8) NOT NULL ,
NUM_LARGO INT (3) DEFAULT NULL,
NUM_ANCHO INT (3) DEFAULT NULL,
NUM_ALTO INT (3) DEFAULT NULL,
PRIMARY KEY (ID_ARTICULO_MEDIADA)
);

CREATE TABLE IF NOT EXISTS SVT_PAQUETE (
	ID_PAQUETE INT(8)  NOT NULL AUTO_INCREMENT,
   NOM_PAQUETE VARCHAR(70) NOT NULL,
   DES_PAQUETE VARCHAR(70) NOT NULL,
mon_COSTO_REFERENCIA DECIMAL(12,2)NOT NULL,
mon_PRECIO DECIMAL(12,2)NOT NULL,
IDN_REGIÓN BIT NOT NULL ,
  `CVE_ESTATUS` BIT(1) NOT NULL,
 `ID_PRODUCTOS_SERVICIOS` INT(2) NOT NULL ,
  `ID_USUARIO_ALTA` INT(5) NOT NULL,
  `FEC_ALTA` DATETIME DEFAULT NULL,
  `FEC_ACTUALIZACION` DATETIME DEFAULT NULL,
  `FEC_BAJA` DATETIME DEFAULT NULL,
  `ID_USUARIO_MODIFICA` VARCHAR(20) DEFAULT NULL,
  `ID_USUARIO_BAJA` VARCHAR(20) DEFAULT NULL,
PRIMARY KEY (ID_PAQUETE));


CREATE TABLE SVT_PAQUETE_ARTICULO (
ID_PAQUETE_ARTICULO INT(8)  NOT NULL AUTO_INCREMENT,
ID_ARTICULO INT(8) NOT NULL,
ID_PAQUETE INT(8)  NOT NULL,
  `CVE_ESTATUS` BIT(1) NOT NULL,
PRIMARY KEY (ID_PAQUETE_ARTICULO),
    CONSTRAINT `SVT_PAQUETE_SERVICIOID_ARTICULO` FOREIGN KEY (`ID_ARTICULO`) REFERENCES `SVT_ARTICULO` (`ID_ARTICULO`),
    CONSTRAINT `SVT_PAQUETE_SERVICIOID_PAQUETE` FOREIGN KEY (`ID_PAQUETE`) REFERENCES `SVT_PAQUETE` (`ID_PAQUETE`)
)
;



CREATE TABLE SVT_PAQUETE_SERVICIO (
ID_PAQUETE_SERVICIO INT (8) NOT NULL AUTO_INCREMENT,
ID_SERVICIO INT(8) NOT NULL,
ID_PAQUETE INT(8)  NOT NULL,
  `CVE_ESTATUS` BIT(1) NOT NULL,
PRIMARY KEY (ID_PAQUETE_SERVICIO),
    CONSTRAINT `SVT_PAQUETE_SERVICIOID_SERVICIO` FOREIGN KEY (`ID_SERVICIO`) REFERENCES `SVT_SERVICIO` (`ID_SERVICIO`),
    CONSTRAINT `SVT_PAQUETE_SERVICIOID_PAQUETE1` FOREIGN KEY (`ID_PAQUETE`) REFERENCES `SVT_PAQUETE` (`ID_PAQUETE`)
)
;
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (1,'RENTA DE CAPILLA.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (2,'RENTA DE EQUIPO PARA VELACIÓN EN DOMICILIO.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (3,'CREMACIÓN.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (4,'TRASLADO.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (5,'EMBALSAMIENTO.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (6,'ARREGLO.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (7,'APOYO PARA TRÁMITES FUNERARIOS.');
INSERT INTO `SVBDQA`.`SVC_TIPO_SERVICIO` (ID_TIPO_SERVICIO,DES_TIPO_SERVICIO) VALUES (8,'OTROS.');

INSERT INTO `SVBDQA`.`SVC_NIVEL_OFICINA` (`ID_OFICINA`, `DES_NIVELOFICINA`) VALUES (1, 'CENTRAL');
INSERT INTO `SVBDQA`.`SVC_NIVEL_OFICINA` (`ID_OFICINA`, `DES_NIVELOFICINA`) VALUES (2, 'DELEGACIONAL');
INSERT INTO `SVBDQA`.`SVC_NIVEL_OFICINA` (`ID_OFICINA`, `DES_NIVELOFICINA`) VALUES (3, 'VELATORIOS');
-- DELEGACION
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (1, 'AGUASCALIENTES');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (02, 'BAJA CALIFORNIA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (03, 'BAJA CALIFORNIA SUR');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (04, 'CAMPECHE');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (05, 'COAHUILA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (06, 'COLIMA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (07, 'CHIAPAS');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (08, 'CHIHUAHUA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (09, 'OFICINAS CENTRALES');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (10, 'DURANGO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (11, 'GUANAJUATO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (12, 'GUERRERO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (13, 'HIDALGO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (14, 'JALISCO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (15, 'EDO DE MEX ORIENTE');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (16, 'EDO DE MEX PONIENTE');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (17, 'MICHOACAN');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (18, 'MORELOS');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (19, 'NAYARIT');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (20, 'NUEVO LEON');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (21, 'OAXACA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (22, 'PUEBLA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (23, 'QUERETARO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (24, 'QUINTANA ROO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (25, 'SAN LUIS POTOSI');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (26, 'SINALOA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (27, 'SONORA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (28, 'TABASCO');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (29, 'TAMAULIPAS');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (30, 'TLAXCALA');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (31, 'VERACRUZ NORTE');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (32, 'VERACRUZ SUR');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (33, 'YUCATAN');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (34, 'ZACATECAS');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (35, '1 NOROESTE D.F.');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (36, '2 NORESTE D.F.');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (37, '3 SUROESTE D.F.');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (38, '4 SURESTE D.F.');
INSERT INTO `SVBDQA`.`SVC_DELEGACION` (`ID_DELEGACION`, `DES_DELEGACION`) VALUES (39, 'NOMINA DE MANDO');

INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (1, 'DOCTORES');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (2, 'CHIHUAHUA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (3, 'MÉRIDA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (4, 'TORREÓN');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (5, 'CIUDAD JUÁREZ');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (6, 'GUADALAJARA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (7, 'TOLUCA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (8, 'MONTERREY');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (9, 'PUEBLA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (10, 'VERACRUZ');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (11, 'QUERÉTARO');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (12, 'SAN LUIS POTOSÍ');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (13, 'PACHUCA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (14, 'TAPACHULA');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (15, 'TEQUESQUITENGO');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (16, 'ECATEPEC');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (17, 'TAMPICO');
INSERT INTO `SVBDQA`.`SVC_VELATORIO` (`ID_VELATORIO`, `NOM_VELATORIO`) VALUES (18, 'VILLA HERMOSA');



-- OFICINA CENTRAL:
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (1,'COORDINADOR DE CENTROS VACACIONALES, VELATORIOS UNIDAD DE CONGRESOS Y TIENDAS');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (2,'JEFE DE DIVISIÓN DE VELATORIOS');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (3,'PERSONAL OPERATIVO DE LA DIVISIÓN DE VELATORIOS ENCARGADO DE REPORTES');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (4,'FBS_DT');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (5,'FBS_SISTEMAS');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (6,'FBS_ADMINISTRACIÓN');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (7,'FBS_FINANZAS');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (8,'FBS_COMERCIALIZACIÓN');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (9,'FBS_NORMATIVIDAD');

-- OFICINA DELEGACIONAL:
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (10,'JEFE DE SERVICIOS DE SALUD EN EL TRABAJO PRESTACIONES ECONÓMICAS Y SOCIALES');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (11,'JEFE DE DEPARTAMENTO DE PRESTACIONES SOCIALES');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (12,'JEFE DE OFICINA DE SOCIALES DE INGRESO');

-- OFICINA VELATORIOS:
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (13,'ADMINISTRADOR');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (14,'COORDINADOR ADMINISTRATIVO');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (15,'COORDINADOR OPERATIVO');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (16,'AGENTE DE FUNERALES');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (17,'APOYO ADMINISTRATIVO');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (18,'CAJA');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (19,'ALMACENISTA');
INSERT INTO `SVBDQA`.`SVC_ROL` (`ID_ROL`, `DES_ROL`) VALUES (20,'PROMOTOR');





-- OFICINA CENTRAL:
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (1,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (2,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (3,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (4,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (5,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (6,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (7,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (8,1);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (9,1);

-- OFICINA DELEGACIONAL:
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (10,2);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (11,2);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (12,2);

-- OFICINA VELATORIOS:
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (13,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (14,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (15,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (16,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (17,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (18,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (19,3);
INSERT INTO `SVBDQA`.`SVC_ROL_NIVEL_OFICINA` (`ID_ROL`, `ID_OFICINA`) VALUES (20,3);

INSERT INTO `SVBDQA`.`SVC_PERMISO` (`ID_PERMISO`, `DES_PERMISO`) VALUES (1, 'ALTA');
INSERT INTO `SVBDQA`.`SVC_PERMISO` (`ID_PERMISO`, `DES_PERMISO`) VALUES (2, 'BAJA'); 
INSERT INTO `SVBDQA`.`SVC_PERMISO` (`ID_PERMISO`, `DES_PERMISO`) VALUES (3, 'CONSULTA');
INSERT INTO `SVBDQA`.`SVC_PERMISO` (`ID_PERMISO`, `DES_PERMISO`) VALUES (4, 'MODIFICAR'); 
INSERT INTO `SVBDQA`.`SVC_PERMISO` (`ID_PERMISO`, `DES_PERMISO`) VALUES (5, 'APROBACIÓN'); 
INSERT INTO `SVBDQA`.`SVC_PERMISO` (`ID_PERMISO`, `DES_PERMISO`) VALUES (6, 'IMPRIMIR');

INSERT INTO `SVBDQA`.`SVC_FUNCIONALIDAD` (`ID_FUNCIONALIDAD`, `DES_FUNCIONALIDAD`) VALUES (1, 'USUARIO CU2');


INSERT INTO `SVBDQA`.`SVC_ROL_FUNCIONALIDAD_PERMISO` (`ID_ROL`, `ID_FUNCIONALIDAD`, `ID_PERMISO`, `CVE_ESTATUS`) VALUES (1, 1, 1, B'0');
INSERT INTO `SVBDQA`.`SVC_ROL_FUNCIONALIDAD_PERMISO` (`ID_ROL`, `ID_FUNCIONALIDAD`, `ID_PERMISO`, `CVE_ESTATUS`) VALUES (1, 1, 2, B'0');
INSERT INTO `SVBDQA`.`SVC_ROL_FUNCIONALIDAD_PERMISO` (`ID_ROL`, `ID_FUNCIONALIDAD`, `ID_PERMISO`, `CVE_ESTATUS`) VALUES (1, 1, 3, B'0');
INSERT INTO `SVBDQA`.`SVC_ROL_FUNCIONALIDAD_PERMISO` (`ID_ROL`, `ID_FUNCIONALIDAD`, `ID_PERMISO`, `CVE_ESTATUS`) VALUES (1, 1, 4, B'0');
INSERT INTO `SVBDQA`.`SVC_ROL_FUNCIONALIDAD_PERMISO` (`ID_ROL`, `ID_FUNCIONALIDAD`, `ID_PERMISO`, `CVE_ESTATUS`) VALUES (1, 1, 5, B'0');
INSERT INTO `SVBDQA`.`SVC_ROL_FUNCIONALIDAD_PERMISO` (`ID_ROL`, `ID_FUNCIONALIDAD`, `ID_PERMISO`, `CVE_ESTATUS`) VALUES (1, 1, 6, B'0');


/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'SYSTEM') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
